### ISSUE TITLE
Please fix the text when ide showing overload funtions

### ISSUE THREAD

**Issue by imxike** [subtheme-pro/solarized#3]
![image](https://user-images.githubusercontent.com/8916625/108614469-47176d00-742d-11eb-8a15-64f2b2681ec7.png)

![image](https://user-images.githubusercontent.com/8916625/108614495-a1183280-742d-11eb-8907-1c46689c44a1.png)

these text is really hard to read. thank you

**Comment by jontaydev** [comment]
I'll take a look

**Comment by jontaydev** [comment]
Can you give me more information how to reproduce this? When I see a function param popup (looking at Java), I only see something similar to the column on the left, but I don't see the right hand section of your screenshot.

Is there a specific repo/file you can point me to perhaps?

I also fixed issue #4 so it's possible that this was addressed, but I'm not sure.

Thanks

**Comment by imxike** [comment]
> 
> 
> Can you give me more information how to reproduce this? When I see a function param popup (looking at Java), I only see something similar to the column on the left, but I don't see the right hand section of your screenshot.
> 
> Is there a specific repo/file you can point me to perhaps?
> 
> I also fixed issue #4 so it's possible that this was addressed, but I'm not sure.
> 
> Thanks

Sorry for not come up with information. I'm using rider and c#. The latest version still the same. Thank you
